### ISSUE TITLE
how to solve this error plz help me bro

### ISSUE THREAD

**Issue by Amitkumar9368** [qorenx/AnitiumNet#2]
Warning: require(/storage/ssd5/347/20977347/public_html/vendor/composer/../phpunit/phpunit/src/Framework/Assert/Functions.php): Failed to open stream: No such file or directory in /storage/ssd5/347/20977347/public_html/vendor/composer/autoload_real.php on line 41

Fatal error: Uncaught Error: Failed opening required '/storage/ssd5/347/20977347/public_html/vendor/composer/../phpunit/phpunit/src/Framework/Assert/Functions.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /storage/ssd5/347/20977347/public_html/vendor/composer/autoload_real.php:41 Stack trace: #0 /storage/ssd5/347/20977347/public_html/vendor/composer/autoload_real.php(45): {closure}() #1 /storage/ssd5/347/20977347/public_html/vendor/autoload.php(25): ComposerAutoloaderInitd107bbad7585179bc163da828ea58eb1::getLoader() #2 /storage/ssd5/347/20977347/public_html/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(136): include('...') #3 /storage/ssd5/347/20977347/public_html/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(125): CodeIgniter\Autoloader\Autoloader->loadComposerInfo() #4 /storage/ssd5/347/20977347/public_html/vendor/codeigniter4/framework/system/bootstrap.php(105): CodeIgniter\Autoloader\Autoloader->initialize() #5 /storage/ssd5/347/20977347/public_html/index.php(38): require('...') #6 {main} thrown in /storage/ssd5/347/20977347/public_html/vendor/composer/autoload_real.php on line 41

**Comment by qorenx** [comment]
It's normal that it won't install. I hide the license files. 2 folders are hidden. If you will use it. You need to be able to install plugins in PHP. We are using something different other than ionCube.

**Comment by Amitkumar9368** [comment]
> It's normal that it won't install. I hide the license files. 2 folders are hidden. If you will use it. You need to be able to install plugins in PHP. We are using something different other than ionCube.

Please help me brother how to install this script tell me the steps

**Comment by qorenx** [comment]
> > It's normal that it won't install. I hide the license files. 2 folders are hidden. If you will use it. You need to be able to install plugins in PHP. We are using something different other than ionCube.
> 
> Please help me brother how to install this script tell me the steps

Join Discord. To the general-en part. Label and write Anit(YT). It's still under development now. You'd better follow the comment system version 1.0 release.
