### ISSUE TITLE
Search function is not working properly with english language

### ISSUE THREAD

**Issue by Hammaduddin561** [qorenx/AnitiumNet#4]
English search function is fine but its not working properly when I search a anime name in English it suggests me right anime
![Screenshot_2023-10-28-23-32-39-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/qorenx/AnitiumNet/assets/67366622/35eb7332-2109-4f52-a533-045fd144b688)

But when I tap the search 
![IMG_20231028_233513](https://github.com/qorenx/AnitiumNet/assets/67366622/b9d4899f-1f7d-4579-aa68-41ffad36132b)

Then it show nothing
![Screenshot_2023-10-28-23-34-57-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/qorenx/AnitiumNet/assets/67366622/ac0d491a-2376-41da-9a0a-d0e46cfdb02e)

Please fix this issue.

**Comment by qorenx** [comment]
Fixed.
